[package]
name = "json-syntax"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
description = "Strict JSON parsing and mapping library"
categories = ["parsing", "data-structures"]
keywords = ["parsing", "json", "rfc", "mapping"]
repository = "https://github.com/timothee-haudebourg/json-syntax"
documentation = "https://docs.rs/json-syntax"
license = "MIT/Apache-2.0"
readme = "README.md"
rust-version = "1.96.0"
edition = "2024"
version = "0.12.5"

[features]
default = ["serde"]

## JSON Canonicalization Scheme (JCS) implementation.
canonicalize = ["dep:ryu-js"]

## Serialization/Deserialization support using `serde`.
serde = ["dep:serde", "smallstr/serde"]

## Compatibility layer with the `serde_json` crate.
serde_json = ["dep:serde_json"]

# Enables the `locspan/miette` feature.
miette = ["locspan/miette"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
smallvec = "1.9"
smallstr = "0.3"
locspan = "1.0"
lexical = { version = "7.0.1", features = [ "format" ] }
decoded-char = "0.1"
btree-indexmap = "1.4"
utf8-decode = "2.0"
into-owned-trait = "1.0"
str-newtype = "3.0"

# Canonicalization.
ryu-js = { version = "0.2.2", optional = true }

# Compatibility with `serde`.
serde = { version = "1.0", optional = true }

# Compatibility with `serde_json`.
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }

[[example]]
name = "serde"
required-features = ["serde"]

[[example]]
name = "serde_json"
required-features = ["serde_json"]
